version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    environment:
      NODE_ENV: development
      DEBUG: "Eleventy*"
    ports:
      - 8080:8080
      - 3001:3001

volumes:
  node_modules: